/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserStoryPanel.java
 *
 * Created on Dec 11, 2012, 1:35:43 AM
 */
package collaboration;

import collaborationjava7.common.Task;
import collaborationjava7.common.UserStory;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Cam
 */
public class UserStoryPanel extends javax.swing.JPanel {
    
    /** Creates new form UserStoryPanel */
    public UserStoryPanel() {
        initComponents();
    }
    Task selectedTask=null;
    UserStory selectedUS=null;
    
    
    private ArrayList<Task> getTasks(){
        if(selectedUS != null){
            return selectedUS.getTasks();
        }
        return new ArrayList<Task>();
    }
    public void updateComponents(){
        this.userStoryList.removeAll();
        this.userStoryList.setModel(new USListModel());
        this.taskList.removeAll();
        this.taskList.setModel(new TaskListModel());
    }
    
    private class TaskListModel extends AbstractListModel{
        ArrayList<Task> tasks = getTasks();
        public int getSize() { return tasks.size(); }
        public Task getElementAt(int i) { return tasks.get(i); }
        public void update(){
            tasks = getTasks();
        }
    }
    private class USListModel extends AbstractListModel{
        ArrayList<UserStory> userStories = getUserStories();
        public int getSize() { return userStories.size(); }
        public UserStory getElementAt(int i) { return userStories.get(i); }
        public void update(){
            userStories = getUserStories();
        }

        private ArrayList<UserStory> getUserStories() {
            ArrayList<UserStory> retVal = null;
            try{
                retVal = mainView.engine.getUserStories();
            }
            catch(Exception e){
                retVal = new ArrayList<UserStory>();
            }
            return retVal;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userStoryList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        taskList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        userStoryTextBox = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        taskTextBox = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        userStoryList.setModel(new USListModel());
        userStoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userStoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userStoryListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(userStoryList);

        taskList.setModel(new TaskListModel());
        taskList.setCellRenderer(new ListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel();
                label.setOpaque(true);
                if (isSelected) {
                    label.setBackground(list.getSelectionBackground());
                    label.setForeground(list.getSelectionForeground());
                }
                else {
                    label.setBackground(list.getBackground());
                    label.setForeground(list.getForeground());
                }
                label.setText(((Task)value).getName());
                Border border = null;
                if (cellHasFocus) {
                    if (isSelected) {
                        border = UIManager.getBorder("List.focusSelectedCellHighlightBorder");
                    }
                    if (border == null) {
                        border = UIManager.getBorder("List.focusCellHighlightBorder");
                    }
                } else {
                    border = new EmptyBorder(1, 1, 1, 1);
                }
                label.setBorder(border);
                return label;
            }
        });
        taskList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        taskList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                taskListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(taskList);

        jScrollPane2.setViewportView(userStoryTextBox);

        jScrollPane4.setViewportView(taskTextBox);

        jLabel1.setText("User Story");

        jLabel2.setText("Description");

        jLabel3.setText("Tasks");

        jLabel4.setText("Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userStoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userStoryListValueChanged
        selectedUS = (UserStory)this.userStoryList.getSelectedValue();
        //this.userStoryTextBox.setText(selectedUS.getDescription());
        this.taskList.setModel(new TaskListModel());
    }//GEN-LAST:event_userStoryListValueChanged

    private void taskListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_taskListValueChanged
        selectedTask = (Task)this.taskList.getSelectedValue();
        if(this.selectedTask != null)
            this.taskTextBox.setText(selectedTask.getDescription());
    }//GEN-LAST:event_taskListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList taskList;
    private javax.swing.JEditorPane taskTextBox;
    private javax.swing.JList userStoryList;
    private javax.swing.JEditorPane userStoryTextBox;
    // End of variables declaration//GEN-END:variables
}
